import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Ground onion",
    price: "350.00",
    color: "fresh red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Avacado",
    price: "180.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Brocolli",
    price: "250.00",
    color: "Mixed",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Peas",
    price: "220.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Ground onion",
    price: "35.00",
    color: "fresh red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Avacado",
    price: "180.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Brocolli",
    price: "250.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Peas",
    price: "220.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Strawberry",
    price: "350.00",
    color: "fresh red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Pumpkin",
    price: "180.00",
    color: "orange",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Brinjal",
    price: "250.00",
    color: "Purple",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "tomato",
    price: "220.00",
    color: "red",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "mango",
    price: "440.00",
    color: "yellow",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "orange",
    price: "250.00",
    color: "orange",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "chilli",
    price: "80.00",
    color: "red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Pineapple",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "pineapple",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "orange",
    price: "250.00",
    color: "orange",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "pineapple",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "tomoto",
    price: "220.00",
    color: "red",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "mango",
    price: "440.00",
    color: "yellow",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "orange",
    price: "250.00",
    color: "orange",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "chilli",
    price: "80.00",
    color: "red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "brocolli",
    price: "250.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "peas",
    price: "220.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "strawberry",
    price: "350.00",
    color: "fresh red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "ground onion",
    price: "350.00",
    color: "fresh red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "avacado",
    price: "180.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "brocolli",
    price: "250.00",
    color: "Mixed",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "peas",
    price: "220.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "strawberry",
    price: "35.00",
    color: "fresh red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "pumpkin",
    price: "180.00",
    color: "yellow",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "brinjal",
    price: "250.00",
    color: "purple",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "tomoto",
    price: "220.00",
    color: "red",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "mango",
    price: "440.00",
    color: "yellow",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "orange",
    price: "250.00",
    color: "orange",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "chilli",
    price: "80.00",
    color: "red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Pineappple",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Pineapple",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Pineapple",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Orange",
    price: "250.00",
    color: "orange",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Tomato",
    price: "220.00",
    color: "fresh red",
    badge: false,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Mango",
    price: "440.00",
    color: "yellow",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Orange",
    price: "250.00",
    color: "orange",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "Chilli",
    price: "80.00",
    color: "red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Brocolli",
    price: "250.00",
    color: "Mixed",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Peas",
    price: "220.00",
    color: "green",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Strawberry",
    price: "350.00",
    color: "fresh red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Ground onion",
    price: "350.00",
    color: "fresh red",
    badge: true,
    des: "Freshly hand picked and hygine is maintained",
  },
];
// =================== PaginationItems End here =================
